### ISSUE TITLE
Images not associated with articles don't have authors

### ISSUE THREAD

**Issue by CyanoKobalamyne** [TheMITTech/thetech.com#495]
This applies to the home page as well as the image page itself. See e.g. https://thetech.com/photos/8968

**Comment by tareqdandachi** [comment]
The broken link seems to be referencing photo no. 896 instead of 8968

**Comment by tareqdandachi** [comment]
<img width="1440" alt="Screen Shot 2019-09-03 at 5 40 32 PM" src="https://user-images.githubusercontent.com/27817478/64210701-f6dfd000-ce71-11e9-8297-9def36c57011.png">

If the referenced image is in fact 896 it seems to *not* have that info filled out already, or at least not saved, which is why no authors exist. If not, then perhaps the same issue had occurred and the image was deleted, therefore cannot debug further. 

A similar issue was highlighted before, turned out the person hadn't saved authors properly and just clicking save did the trick. Will close the issue until a time where the issue persists.
